/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_agora_avmodule_AvNativeDiagnose */

#ifndef _Included_io_agora_avmodule_AvNativeDiagnose
#define _Included_io_agora_avmodule_AvNativeDiagnose
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_agora_avmodule_AvNativeDiagnose
 * Method:    native_diagnoseOpen
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_agora_avmodule_AvNativeDiagnose_native_1diagnoseOpen
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_agora_avmodule_AvNativeDiagnose
 * Method:    native_diagnoseClose
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvNativeDiagnose_native_1diagnoseClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_agora_avmodule_AvNativeDiagnose
 * Method:    native_diagnoseGetMediaInfo
 * Signature: (JLio/agora/avmodule/AvMediaInfo;)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvNativeDiagnose_native_1diagnoseGetMediaInfo
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     io_agora_avmodule_AvNativeDiagnose
 * Method:    native_diagnoseDoStep
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvNativeDiagnose_native_1diagnoseDoStep
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_agora_avmodule_AvNativeDiagnose
 * Method:    native_diagnoseGetProgress
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_agora_avmodule_AvNativeDiagnose_native_1diagnoseGetProgress
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
